# GNU Make solution makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GlewLib_config = debug
  HnS_config = debug
endif
ifeq ($(config),release)
  GlewLib_config = release
  HnS_config = release
endif

PROJECTS := GlewLib HnS

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GlewLib:
ifneq (,$(GlewLib_config))
	@echo "==== Building GlewLib ($(GlewLib_config)) ===="
	@${MAKE} --no-print-directory -C GlewLib/build -f Makefile config=$(GlewLib_config)
endif

HnS: GlewLib
ifneq (,$(HnS_config))
	@echo "==== Building HnS ($(HnS_config)) ===="
	@${MAKE} --no-print-directory -C HacknSlay_Project/build -f Makefile config=$(HnS_config)
endif

clean:
	@${MAKE} --no-print-directory -C GlewLib/build -f Makefile clean
	@${MAKE} --no-print-directory -C HacknSlay_Project/build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GlewLib"
	@echo "   HnS"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
